---
- hosts: webserver
  become: true
  tasks:
   - name: install apache2 
     apt: name={{item}} state=present update_cache=yes
     with_items:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv

   - name: ensure Apache started
     service: name=apache2 state=started enabled=yes

   - name: ensure mod-wsgi enabled
     apache2_module: state=present name=wsgi
     notify: 
      restart apache2
     
   - name: copy visualapp app source
     copy: src=/home/vagrant/repo/ansible/visualapp/app/  dest=/var/www/visualapp mode=0775
     notify: restart apache2
  
   - name: copy apache virtual host config
     copy: src=/home/vagrant/repo/ansible/visualapp/visualapp.conf dest=/etc/apache2/sites-available mode=0775
     notify: restart apache2

   - name: setup python virtualenv
     pip: requirements=/var/www/visualapp/requirements.txt virtualenv=/var/www/visualapp/.venu
     notify: restart apache2

  handlers:
   - name: restart apache2
     service: name=apache2 state=restarted

  

